# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STD', 'student'), ('MNG', 'management'), ('PRT', 'parent'), ('TCH', 'teacher')], max_length=3),
        ),
    ]
