# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180517_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='name_in_admin',
            field=models.CharField(default='management', max_length=10),
        ),
        migrations.AddField(
            model_name='parent',
            name='name_in_admin',
            field=models.CharField(default='parent', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='name_in_admin',
            field=models.CharField(default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_in_admin',
            field=models.CharField(default='teacher', max_length=10),
        ),
    ]
